{
 "title": "edge_datasource_sensehat",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "온도 및 습도",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "room_temperature{job=\"sensehat\"}",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "room_humidity{job=\"sensehat\"}"
    }
   ]
  },
  {
   "title": "기압",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "room_pressure{job=\"sensehat\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "ACC 가속도",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 7, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "room_accx{job=\"sensehat\"}",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "room_accy{job=\"sensehat\"}"
    },
    {
     "expr": "room_accz{job=\"sensehat\"}"
    }
   ]
  },
  {
   "title": "Gyro 자이로",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 7, "x": 7, "y": 9 },
   "targets": [
    {
     "expr": "room_gyrox{job=\"sensehat\"}",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "room_gyroy{job=\"sensehat\"}"
    },
    {
     "expr": "room_gyroz{job=\"sensehat\"}"
    }
   ]
  },
  {
   "title": "Orientation 방향",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 10, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "room_color_r{job=\"sensehat\"}",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "room_gyroy{job=\"sensehat\"}"
    },
    {
     "expr": "room_color_b{job=\"sensehat\"}"
    }
   ]
  }
 ]
}