# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfile.proto\"!\n\x0f\x46ileDownloadRsp\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\"\x1f\n\x0f\x46ileDownloadReq\x12\x0c\n\x04name\x18\x01 \x01(\t\"\t\n\x07ListReq\"%\n\x07ListRsp\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x03\x32Z\n\x04\x46ile\x12\x32\n\x08\x64ownload\x12\x10.FileDownloadReq\x1a\x10.FileDownloadRsp\"\x00\x30\x01\x12\x1e\n\x04list\x12\x08.ListReq\x1a\x08.ListRsp\"\x00\x30\x01\x62\x06proto3')



_FILEDOWNLOADRSP = DESCRIPTOR.message_types_by_name['FileDownloadRsp']
_FILEDOWNLOADREQ = DESCRIPTOR.message_types_by_name['FileDownloadReq']
_LISTREQ = DESCRIPTOR.message_types_by_name['ListReq']
_LISTRSP = DESCRIPTOR.message_types_by_name['ListRsp']
FileDownloadRsp = _reflection.GeneratedProtocolMessageType('FileDownloadRsp', (_message.Message,), {
  'DESCRIPTOR' : _FILEDOWNLOADRSP,
  '__module__' : 'file_pb2'
  # @@protoc_insertion_point(class_scope:FileDownloadRsp)
  })
_sym_db.RegisterMessage(FileDownloadRsp)

FileDownloadReq = _reflection.GeneratedProtocolMessageType('FileDownloadReq', (_message.Message,), {
  'DESCRIPTOR' : _FILEDOWNLOADREQ,
  '__module__' : 'file_pb2'
  # @@protoc_insertion_point(class_scope:FileDownloadReq)
  })
_sym_db.RegisterMessage(FileDownloadReq)

ListReq = _reflection.GeneratedProtocolMessageType('ListReq', (_message.Message,), {
  'DESCRIPTOR' : _LISTREQ,
  '__module__' : 'file_pb2'
  # @@protoc_insertion_point(class_scope:ListReq)
  })
_sym_db.RegisterMessage(ListReq)

ListRsp = _reflection.GeneratedProtocolMessageType('ListRsp', (_message.Message,), {
  'DESCRIPTOR' : _LISTRSP,
  '__module__' : 'file_pb2'
  # @@protoc_insertion_point(class_scope:ListRsp)
  })
_sym_db.RegisterMessage(ListRsp)

_FILE = DESCRIPTOR.services_by_name['File']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FILEDOWNLOADRSP._serialized_start=14
  _FILEDOWNLOADRSP._serialized_end=47
  _FILEDOWNLOADREQ._serialized_start=49
  _FILEDOWNLOADREQ._serialized_end=80
  _LISTREQ._serialized_start=82
  _LISTREQ._serialized_end=91
  _LISTRSP._serialized_start=93
  _LISTRSP._serialized_end=130
  _FILE._serialized_start=132
  _FILE._serialized_end=222
# @@protoc_insertion_point(module_scope)
