# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import file_pb2 as file__pb2


class FileStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.download = channel.unary_stream(
                '/File/download',
                request_serializer=file__pb2.FileDownloadReq.SerializeToString,
                response_deserializer=file__pb2.FileDownloadRsp.FromString,
                )
        self.list = channel.unary_stream(
                '/File/list',
                request_serializer=file__pb2.ListReq.SerializeToString,
                response_deserializer=file__pb2.ListRsp.FromString,
                )


class FileServicer(object):
    """Missing associated documentation comment in .proto file."""

    def download(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def list(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'download': grpc.unary_stream_rpc_method_handler(
                    servicer.download,
                    request_deserializer=file__pb2.FileDownloadReq.FromString,
                    response_serializer=file__pb2.FileDownloadRsp.SerializeToString,
            ),
            'list': grpc.unary_stream_rpc_method_handler(
                    servicer.list,
                    request_deserializer=file__pb2.ListReq.FromString,
                    response_serializer=file__pb2.ListRsp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'File', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class File(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def download(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/File/download',
            file__pb2.FileDownloadReq.SerializeToString,
            file__pb2.FileDownloadRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def list(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/File/list',
            file__pb2.ListReq.SerializeToString,
            file__pb2.ListRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
