---
- hosts: all
  remote_user: jpark
  become: true
  become_method: sudo
  tasks:
    - name: Update apt repo and cache on all boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on Pi's
      apt: upgrade=dist force_apt_get=yes

    - name: Check if a reboot is needed on all Pi's
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

#    - name: Reboot the Pi's if kernel updated
#      reboot:
#        msg: "Reboot initiated by Ansible for kernel updates"
#        connect_timeout: 5
#        reboot_timeout: 300
#        pre_reboot_delay: 0
#        post_reboot_delay: 30
#        test_command: uptime
#      when: reboot_required_file.stat.exists
