---
- hosts: all
  remote_user: jpark
  become: true
  become_method: sudo
  tasks:
    - name: Update apt repo and cache on all boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on Pi's
      apt: upgrade=dist force_apt_get=yes

    - name: Show Time Date Control
      shell: timedatectl status
      register: msg 
    - debug: msg="{{msg.stdout}}"

    - name: Install ntp
      apt:
        name : ntp
        state : present

    - name: ntp status
      shell: |
        service ntp status
      register: msg
    - debug: msg="{{msg.stdout}}"

    - name: Install ntpdate
      apt:
        name : ntpdate
        state : present

    - name: Time sync with ntpdate 
      shell: ntpdate -q 0.us.pool.ntp.org  
      register: msg 
    - debug: msg="{{msg.stdout}}"


    - name: Show Time Date Control
      shell: timedatectl status
      register: msg 
    - debug: msg="{{msg.stdout}}"

    - name: Show microsec resolution time (us) 
      shell: | 
        expr `date +%s%N` / 1000
      register: msg 
    - debug: msg="{{msg.stdout}}"

