# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/file.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protos/file.proto\"\x1b\n\tFileChunk\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\"#\n\x13\x46ileDownloadRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\'\n\x12\x46ileUploadResponse\x12\x11\n\tfile_size\x18\x01 \x01(\x05\"\r\n\x0bListRequest\"*\n\x0cListResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x03\x32\x90\x01\n\x04\x46ile\x12\x30\n\x08\x64ownload\x12\x14.FileDownloadRequest\x1a\n.FileChunk\"\x00\x30\x01\x12-\n\x06upload\x12\n.FileChunk\x1a\x13.FileUploadResponse\"\x00(\x01\x12\'\n\x04list\x12\x0c.ListRequest\x1a\r.ListResponse\"\x00\x30\x01\x62\x06proto3')



_FILECHUNK = DESCRIPTOR.message_types_by_name['FileChunk']
_FILEDOWNLOADREQUEST = DESCRIPTOR.message_types_by_name['FileDownloadRequest']
_FILEUPLOADRESPONSE = DESCRIPTOR.message_types_by_name['FileUploadResponse']
_LISTREQUEST = DESCRIPTOR.message_types_by_name['ListRequest']
_LISTRESPONSE = DESCRIPTOR.message_types_by_name['ListResponse']
FileChunk = _reflection.GeneratedProtocolMessageType('FileChunk', (_message.Message,), {
  'DESCRIPTOR' : _FILECHUNK,
  '__module__' : 'protos.file_pb2'
  # @@protoc_insertion_point(class_scope:FileChunk)
  })
_sym_db.RegisterMessage(FileChunk)

FileDownloadRequest = _reflection.GeneratedProtocolMessageType('FileDownloadRequest', (_message.Message,), {
  'DESCRIPTOR' : _FILEDOWNLOADREQUEST,
  '__module__' : 'protos.file_pb2'
  # @@protoc_insertion_point(class_scope:FileDownloadRequest)
  })
_sym_db.RegisterMessage(FileDownloadRequest)

FileUploadResponse = _reflection.GeneratedProtocolMessageType('FileUploadResponse', (_message.Message,), {
  'DESCRIPTOR' : _FILEUPLOADRESPONSE,
  '__module__' : 'protos.file_pb2'
  # @@protoc_insertion_point(class_scope:FileUploadResponse)
  })
_sym_db.RegisterMessage(FileUploadResponse)

ListRequest = _reflection.GeneratedProtocolMessageType('ListRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTREQUEST,
  '__module__' : 'protos.file_pb2'
  # @@protoc_insertion_point(class_scope:ListRequest)
  })
_sym_db.RegisterMessage(ListRequest)

ListResponse = _reflection.GeneratedProtocolMessageType('ListResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTRESPONSE,
  '__module__' : 'protos.file_pb2'
  # @@protoc_insertion_point(class_scope:ListResponse)
  })
_sym_db.RegisterMessage(ListResponse)

_FILE = DESCRIPTOR.services_by_name['File']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FILECHUNK._serialized_start=21
  _FILECHUNK._serialized_end=48
  _FILEDOWNLOADREQUEST._serialized_start=50
  _FILEDOWNLOADREQUEST._serialized_end=85
  _FILEUPLOADRESPONSE._serialized_start=87
  _FILEUPLOADRESPONSE._serialized_end=126
  _LISTREQUEST._serialized_start=128
  _LISTREQUEST._serialized_end=141
  _LISTRESPONSE._serialized_start=143
  _LISTRESPONSE._serialized_end=185
  _FILE._serialized_start=188
  _FILE._serialized_end=332
# @@protoc_insertion_point(module_scope)
