# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import file_pb2 as protos_dot_file__pb2


class FileStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.download = channel.unary_stream(
                '/File/download',
                request_serializer=protos_dot_file__pb2.FileDownloadRequest.SerializeToString,
                response_deserializer=protos_dot_file__pb2.FileChunk.FromString,
                )
        self.upload = channel.stream_unary(
                '/File/upload',
                request_serializer=protos_dot_file__pb2.FileChunk.SerializeToString,
                response_deserializer=protos_dot_file__pb2.FileUploadResponse.FromString,
                )
        self.list = channel.unary_stream(
                '/File/list',
                request_serializer=protos_dot_file__pb2.ListRequest.SerializeToString,
                response_deserializer=protos_dot_file__pb2.ListResponse.FromString,
                )


class FileServicer(object):
    """Missing associated documentation comment in .proto file."""

    def download(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def upload(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def list(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'download': grpc.unary_stream_rpc_method_handler(
                    servicer.download,
                    request_deserializer=protos_dot_file__pb2.FileDownloadRequest.FromString,
                    response_serializer=protos_dot_file__pb2.FileChunk.SerializeToString,
            ),
            'upload': grpc.stream_unary_rpc_method_handler(
                    servicer.upload,
                    request_deserializer=protos_dot_file__pb2.FileChunk.FromString,
                    response_serializer=protos_dot_file__pb2.FileUploadResponse.SerializeToString,
            ),
            'list': grpc.unary_stream_rpc_method_handler(
                    servicer.list,
                    request_deserializer=protos_dot_file__pb2.ListRequest.FromString,
                    response_serializer=protos_dot_file__pb2.ListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'File', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class File(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def download(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/File/download',
            protos_dot_file__pb2.FileDownloadRequest.SerializeToString,
            protos_dot_file__pb2.FileChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def upload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/File/upload',
            protos_dot_file__pb2.FileChunk.SerializeToString,
            protos_dot_file__pb2.FileUploadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def list(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/File/list',
            protos_dot_file__pb2.ListRequest.SerializeToString,
            protos_dot_file__pb2.ListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
