FROM alpine:latest

# Install necessary packages
RUN apk update && apk add --no-cache \
    bash \
    curl \
    lm_sensors \
    util-linux

# Copy scripts into the image
COPY beacon_arm.sh /usr/local/bin/beacon_arm.sh

# Make scripts executable
RUN chmod +x /usr/local/bin/beacon_arm.sh

# Set entrypoint
CMD ["/bin/bash", "-c", "/usr/local/bin/beacon_arm.sh"]

