{
 "title": "EdgeFramework_admin",
 "description": "monitor all registered nodes",
 "tags": [ "bhc" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "node list",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "select * from nodes;",
     "rawQueryText": "select * from nodes;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Location",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "queryText": "select CAST(latitude as real) as lat, CAST(longitude as real) as lng, name from location;",
     "rawQueryText": "select CAST(latitude as real) as lat, CAST(longitude as real) as lng, name from location;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "rpi6402",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 2, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select CAST(capacity as real) as capicty, CAST(inuse as real) as inuse, name from strginfo where name = 'rpi6402' order by ROWID desc limit 1;",
     "rawQueryText": "select CAST(capacity as real) as capicty, CAST(inuse as real) as inuse, name from strginfo where name = 'rpi6402' order by ROWID desc limit 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "rpi6403",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select CAST(capacity as real) as capicty, CAST(inuse as real) as inuse, name from strginfo where name = 'rpi6403' order by ROWID desc limit 1;",
     "rawQueryText": "select CAST(capacity as real) as capicty, CAST(inuse as real) as inuse, name from strginfo where name = 'rpi6403' order by ROWID desc limit 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "rpi6404",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select CAST(capacity as real) as capicty, CAST(inuse as real) as inuse, name from strginfo where name = 'rpi6404' order by ROWID desc limit 1;",
     "rawQueryText": "select CAST(capacity as real) as capicty, CAST(inuse as real) as inuse, name from strginfo where name = 'rpi6404' order by ROWID desc limit 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "rpi6405",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select CAST(capacity as real) as capicty, CAST(inuse as real) as inuse, name from strginfo where name = 'rpi6405' order by ROWID desc limit 1;",
     "rawQueryText": "select CAST(capacity as real) as capicty, CAST(inuse as real) as inuse, name from strginfo where name = 'rpi6405' order by ROWID desc limit 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "rpi6406",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select CAST(capacity as real) as capicty, CAST(inuse as real) as inuse, name from strginfo where name = 'rpi6406' order by ROWID desc limit 1;",
     "rawQueryText": "select CAST(capacity as real) as capicty, CAST(inuse as real) as inuse, name from strginfo where name = 'rpi6406' order by ROWID desc limit 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "current temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select CAST(temperature as real), name from time_temp where name = 'rpi6402' order by ROWID desc limit 1;",
     "rawQueryText": "select CAST(temperature as real), name from time_temp where name = 'rpi6402' order by ROWID desc limit 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "select CAST(temperature as real), name from time_temp where name = 'rpi6403' order by ROWID desc limit 1;",
     "rawQueryText": "select CAST(temperature as real), name from time_temp where name = 'rpi6403' order by ROWID desc limit 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "select CAST(temperature as real), name from time_temp where name = 'rpi6404' order by ROWID desc limit 1;",
     "rawQueryText": "select CAST(temperature as real), name from time_temp where name = 'rpi6404' order by ROWID desc limit 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "select CAST(temperature as real), name from time_temp where name = 'rpi6405' order by ROWID desc limit 1;",
     "rawQueryText": "select CAST(temperature as real), name from time_temp where name = 'rpi6405' order by ROWID desc limit 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "select CAST(temperature as real), name from time_temp where name = 'rpi6406' order by ROWID desc limit 1;",
     "rawQueryText": "select CAST(temperature as real), name from time_temp where name = 'rpi6406' order by ROWID desc limit 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "queryText": "select time, name, CAST(memratio as real) from meminfo;",
     "rawQueryText": "select time, name, CAST(memratio as real) from meminfo;",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "node temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "queryText": "select time, name, CAST(temperature as real) from time_temp;",
     "rawQueryText": "select time, name, CAST(temperature as real) from time_temp;",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "queryText": "select time, name, CAST(100 - cpuratio as real) from cpuinfo;",
     "rawQueryText": "select time, name, CAST(100 - cpuratio as real) from cpuinfo;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}