{
 "title": "RPI 6402",
 "description": "monitor individual node",
 "tags": [ "bhc" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Storage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select CAST(capacity as real) as capicty, CAST(inuse as real) as inuse, name from strginfo where name = 'rpi6402' order by ROWID desc limit 1;",
     "rawQueryText": "select CAST(capacity as real) as capicty, CAST(inuse as real) as inuse, name from strginfo where name = 'rpi6402' order by ROWID desc limit 1;",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Current Temperature",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select CAST(temperature as real), name from time_temp where name = 'rpi6402' order by ROWID desc limit 1;",
     "rawQueryText": "select CAST(temperature as real), name from time_temp where name = 'rpi6402' order by ROWID desc limit 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "queryText": "select time, name, CAST(100 - cpuratio as real) from cpuinfo where name='rpi6402';",
     "rawQueryText": "select time, name, CAST(100 - cpuratio as real) from cpuinfo where name='rpi6402';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "queryText": "select time, name, CAST(memratio as real) from meminfo where name='rpi6402';",
     "rawQueryText": "select time, name, CAST(memratio as real) from meminfo where name='rpi6402';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Time - Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "queryText": "select time, name, CAST(temperature as real) from time_temp where name='rpi6402';",
     "rawQueryText": "select time, name, CAST(temperature as real) from time_temp where name='rpi6402';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Model List",
   "type": "table",
   "gridPos": { "h": 21, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "queryText": "select name, tag from model_list;",
     "rawQueryText": "select name, tag from model_list;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Traffic - IN",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "queryText": "select time, name, CAST(rx_bps as real) from traffic;",
     "rawQueryText": "select time, name, CAST(rx_bps as real) from traffic;",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "TRAFFIC - OUT",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 8 },
   "targets": [
    {
     "queryText": "select time, name, cast(tx_bps as real) from traffic;",
     "rawQueryText": "select time, name, cast(tx_bps as real) from traffic;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Progress",
   "type": "canvas",
   "gridPos": { "h": 6, "w": 8, "x": 2, "y": 13 },
   "targets": [
    {
     "queryText": "select status from dstrb_progress order by ROWID desc limit 1;",
     "rawQueryText": "select status from dstrb_progress order by ROWID desc limit 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Model Description",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 13 },
   "targets": [
    {
     "queryText": "select desc from model_desc where node='rpi6402';",
     "rawQueryText": "select desc from model_desc where node='rpi6402';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}